global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      5s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets:
    - '10.230.105.90:6789'
  metrics_path: /actuator/prometheus
  tls_config:
    insecure_skip_verify: true
  basic_auth:
    username: admin
    password: admin1
