global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10h

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets:
    - '10.230.105.90:6789'
  metrics_path: /actuator/prometheus
  tls_config:
    insecure_skip_verify: true
